"""add business line tables

Revision ID: 209a086023df
Revises: 2adcbe1f5dfb
Create Date: 2025-06-23 03:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
import models as models

# revision identifiers, used by Alembic.
revision = '209a086023df'
down_revision = '2adcbe1f5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'business_lines',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='business_line_pkey')
    )
    op.create_table(
        'account_business_line',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('account_id', sa.String(length=255), nullable=False),
        sa.Column('business_line_id', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Integer(), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='account_business_line_pkey')
    )
    with op.batch_alter_table('account_business_line', schema=None) as batch_op:
        batch_op.create_index('account_business_line_account_bl_idx', ['account_id', 'business_line_id'], unique=False)

    op.create_table(
        'app_business_line',
        sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('app_id', sa.String(length=255), nullable=False),
        sa.Column('account_id', sa.String(length=255), nullable=False),
        sa.Column('business_line_id', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Integer(), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='app_business_line_pkey')
    )
    with op.batch_alter_table('app_business_line', schema=None) as batch_op:
        batch_op.create_index('app_business_line_app_bl_idx', ['app_id', 'business_line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_business_line', schema=None) as batch_op:
        batch_op.drop_index('app_business_line_app_bl_idx')
    op.drop_table('app_business_line')

    with op.batch_alter_table('account_business_line', schema=None) as batch_op:
        batch_op.drop_index('account_business_line_account_bl_idx')
    op.drop_table('account_business_line')

    op.drop_table('business_lines')
    # ### end Alembic commands ###
